CREATE TABLE IF NOT EXISTS EVENT_DETAILS  (
    EVENT_ID SERIAL,
	AUDIT_LOG_TRACE_ID VARCHAR(36),
	LOGGED_BY VARCHAR(36),
	DTTM VARCHAR(30),
	ENTITY_ID VARCHAR(36),
	USER_ID VARCHAR(36),
	SERVICE VARCHAR(20),
	SERVICE_DTTM VARCHAR(30),
	OPERATION VARCHAR(20),
	ENVIRONMET VARCHAR(20),
	ENELX_TRACE_ID VARCHAR(36),
	LOCATION_HOST VARCHAR(20),
	LOCATION_PATH VARCHAR(20),
	ERROR_VALIDATION JSONB
);

CREATE TABLE IF NOT EXISTS EVENT_DIFFERENCES (
    EVENT_DIFF_ID SERIAL,
	AUDIT_LOG_TRACE_ID VARCHAR(36),
	KEY VARCHAR(30),
	FROM_VALUE VARCHAR(60),
	TO_VALUE VARCHAR(60)	
);